demo/demo/accounts/urls.py
from django.urls import path

from .views import ProfileView


urlpatterns = [
    path('', ProfileView.as_view(), name='user-profile'),
]

demo/demo/pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'


urlpatterns = [
    path('', views.index, name='root'),
    path('welcome/<token>/', views.confirm_email, name='confirm-email'),
]

demo/demo/urls.py
"""demo URL Configuration."""

from django.urls import include, path
from django.contrib import admin

from rest_framework.documentation import include_docs_urls
from rest_framework.renderers import DocumentationRenderer

from rest_auth_toolkit.views import (
    EmailConfirmationView,
    FacebookLoginView,
    LoginView,
    LogoutView,
    SignupView,
)


class GoAwayRenderer(DocumentationRenderer):
    # Hide unwanted coreapi code snippets
    languages = []


auth_urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('confirm/', EmailConfirmationView.as_view(), name='confirm'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('fb-login/', FacebookLoginView.as_view(), name='fb-login'),
]

api_urlpatterns = [
    path('account/', include('demo.accounts.urls')),
    path('', include_docs_urls(title='Demo API', permission_classes=[],
                               renderer_classes=[GoAwayRenderer])),
    path('', include((auth_urlpatterns, 'auth'))),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(api_urlpatterns)),
    path('', include('demo.pages.urls')),
]

demo/demo/accounts/models.py
from django.contrib.auth.models import Group as BaseGroup
from django.db import models
from django.utils.translation import gettext_lazy as _

from model_utils.fields import AutoCreatedField
from model_utils.models import TimeStampedModel
from shortuuid.django_fields import ShortUUIDField

from rest_auth_toolkit.managers import BaseEmailUserManager
from rest_auth_toolkit.models import BaseEmailUser, BaseAPIToken, BaseEmailConfirmation


class UserManager(BaseEmailUserManager):
    def get_or_create_facebook_user(self, facebook_data, facebook_access_token):
        try:
            user = User.objects.get(email=facebook_data['email'])
        except User.DoesNotExist:
            user = self.create_user(
                email=facebook_data['email'],
                first_name=facebook_data['first_name'],
                last_name=facebook_data['last_name'],
                facebook_id=facebook_data['third_party_id'],
                facebook_access_token=facebook_access_token,
                is_active=True,
            )
            return user, True
        else:
            user.facebook_access_token = facebook_access_token
            user.save(update_fields=['facebook_access_token'])
            return user, False


class User(BaseEmailUser):
    facebook_id = models.CharField(
        max_length=255, null=True, blank=True, help_text=_('FB third-party ID'))
    facebook_access_token = models.CharField(
        max_length=255, null=True, blank=True, help_text=_('FB access token'))

    objects = UserManager()


class Group(BaseGroup):
    """Proxy model to have users and groups together in admin."""
    class Meta:
        proxy = True
        verbose_name = _('group')
        verbose_name_plural = _('groups')


class EmailConfirmation(BaseEmailConfirmation, TimeStampedModel):
    external_id = ShortUUIDField()


class APIToken(BaseAPIToken, models.Model):
    created = AutoCreatedField(_('created'))

demo/demo/accounts/views.py
from rest_framework import serializers, views
from rest_framework.response import Response

from .models import User


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'date_joined')


class ProfileView(views.APIView):
    """Example view protected by token auth."""

    def get(self, request):
        serializer = UserSerializer(request.user)
        return Response(serializer.data)

demo/demo/pages/views.py
from django.conf import settings
from django.shortcuts import render
from django.utils.translation import gettext as _

from ..accounts.models import EmailConfirmation


def index(request):
    """Site root page."""
    ctx = {
        'site_name': 'Demo',
        'fb_app_id': settings.FACEBOOK_APP_ID,
    }
    return render(request, 'index.html', context=ctx)


def confirm_email(request, token):
    """Landing page for links in confirmation emails."""
    error = None

    try:
        confirmation = EmailConfirmation.objects.get(external_id=token)
        confirmation.confirm()
    except EmailConfirmation.DoesNotExist:
        error = _('Invalid link')
    except EmailConfirmation.IsExpired:
        error = _('Email expired, please register again')

    if error:
        ctx = {
            'site_name': 'Demo',
            'error': error,
        }
        return render(request, 'error.html', context=ctx)
    else:
        ctx = {
            'site_name': 'Demo',
            'email': confirmation.user.email,
        }
        return render(request, 'welcome.html', context=ctx)

demo/demo/accounts/templates/rest_auth_toolkit/email_confirmation.html
{% load i18n demotags %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="background-color: #F7F8FA;">
<div>

<p>
  {% trans "Follow this link to validate your email:" %}<br>
  {% url "pages:confirm-email" token=confirmation.external_id as confirmation_url %}
  {% frontend_base_url as base_url %}
  <a href="{{ base_url }}{{ confirmation_url }}">{{ base_url }}{{ confirmation_url }}</a>
</p>

<p>
  {% trans "Or send an API request to simulate a front-end application:" %}<br>
  <code>HTTP POST {{ base_url }}{% url "auth:confirm" %} email="{{ user.email }}" token="{{ confirmation.external_id }}"</code>
</p>

</div>
</body>
</html>

demo/demo/pages/templates/base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% block body %}{% endblock %}
</body>
</html>

demo/demo/pages/templates/error.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Error! {{ site_name }}{% endblock %}

{% block body %}
<div>
  <h1>{% trans "Error!" %}</h1>
  <p>{{ error }}</p>
</div>
{% endblock %}

demo/demo/pages/templates/index.html
{% extends "base.html" %}
{% block title %}{{ site_name }}{% endblock %}

{% block body %}
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: "{{ fb_app_id }}", xfbml: true, version: "v2.9"});
  };

  function fb_login() {
    FB.login(function(response) {
      $.ajax({
        url: "{% url "auth:fb-login" %}",
        method: "POST",
        contentType: "application/json",
        data: JSON.stringify({signed_request: response.authResponse.signedRequest}),
      });
    }, {"scope": "public_profile,email"});
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id; js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, "script", "facebook-jssdk"));
</script>

<div id="fb-root"></div>

<div>
  <h1>Hello world!</h1>
  <button onclick="fb_login()">Login with Facebook</button>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
{% endblock %}

demo/demo/pages/templates/welcome.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Success! {{ site_name }}{% endblock %}

{% block body %}
<div>
  <h1>{% trans "Success!" %}</h1>
  <p>Your address {{ email }} is now confirmed.</p>
</div>
{% endblock %}